package com.kage049754.campusos

import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Modifier
import androidx.compose.ui.Alignment
import androidx.compose.ui.unit.dp
import androidx.compose.ui.text.font.FontWeight
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale

private data class TaskInfo(val type:String="Assignment",val priority:String="Medium",val status:String="Not started",val reminder:String="",val link:String="",val location:String="",val semester:String="2026–2027 • 1st Semester",val archived:Boolean=false,val pinned:Boolean=false,val notes:String="",val subtasks:List<Pair<String,Boolean>>=emptyList())
private fun taskInfo(r:Record):TaskInfo=runCatching{val o=JSONObject(r.extra);val a=o.optJSONArray("subtasks")?:JSONArray();TaskInfo(o.optString("type","Assignment"),o.optString("priority","Medium"),o.optString("status",if(r.done)"Completed" else "Not started"),o.optString("reminder"),o.optString("link"),o.optString("location"),o.optString("semester","2026–2027 • 1st Semester"),o.optBoolean("archived"),o.optBoolean("pinned"),o.optString("notes"),(0 until a.length()).mapNotNull{i->a.optJSONObject(i)?.let{it.optString("title") to it.optBoolean("done")}})}.getOrElse{TaskInfo(notes=r.extra)}
private fun taskExtra(m:TaskInfo):String{val a=JSONArray();m.subtasks.forEach{(t,d)->a.put(JSONObject().apply{put("title",t);put("done",d)})};return JSONObject().apply{put("type",m.type);put("priority",m.priority);put("status",m.status);put("reminder",m.reminder);put("link",m.link);put("location",m.location);put("semester",m.semester);put("archived",m.archived);put("pinned",m.pinned);put("notes",m.notes);put("subtasks",a)}.toString()}
private fun taskDay(n:Int=0)=SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).format(Calendar.getInstance().apply{add(Calendar.DAY_OF_YEAR,n)}.time)

@Composable
fun TasksRedesignedScreen(store:LocalStore,query:String,clear:()->Unit,openSubject:(Record)->Unit){
    val rev=store.revision;var refresh by remember{mutableIntStateOf(0)};var view by rememberSaveable{mutableStateOf("List")};var status by rememberSaveable{mutableStateOf("All")};var due by rememberSaveable{mutableStateOf("All")};var priority by rememberSaveable{mutableStateOf("All")};var type by rememberSaveable{mutableStateOf("All")};var subject by rememberSaveable{mutableLongStateOf(0)};var archived by rememberSaveable{mutableStateOf(false)};var date by rememberSaveable{mutableStateOf(taskDay())};var edit by remember{mutableStateOf<Record?>(null)};var add by remember{mutableStateOf(false)}
    val all=remember(rev,refresh){store.get("tasks")};val subjects=store.get("subjects");val today=taskDay()
    val list=all.filter{r->val m=taskInfo(r);val q=query.isBlank()||query=="__ADD__"||(r.title+" "+r.subtitle+" "+m.notes+" "+m.type+" "+m.location+" "+m.link).contains(query,true);q&&(status=="All"||(status=="To Do"&&!r.done&&m.status!="In progress")||m.status.equals(status,true))&&(when(due){"Today"->r.dueDate==today;"Tomorrow"->r.dueDate==taskDay(1);"This Week"->r.dueDate in today..taskDay(7);"Overdue"->!r.done&&r.dueDate.isNotBlank()&&r.dueDate<today;else->true})&&(priority=="All"||m.priority==priority)&&(type=="All"||m.type==type)&&(subject==0L||r.subjectId==subject)&&m.archived==archived}.sortedWith(compareBy<Record>({it.done},{!taskInfo(it).pinned},{it.dueDate.ifBlank{"9999-99-99"}},{it.dueTime}))
    val done=all.count{it.done};val overdue=all.count{!it.done&&it.dueDate.isNotBlank()&&it.dueDate<today};val soon=all.count{!it.done&&it.dueDate in today..taskDay(7)}
    Column(Modifier.fillMaxSize()){
        LazyColumn(Modifier.weight(1f),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
            item{Text("Tasks",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Good "+if(Calendar.getInstance().get(Calendar.HOUR_OF_DAY)<12)"morning" else "evening"+", "+store.profileName().ifBlank{"Student"}+" 👋",style=MaterialTheme.typography.titleMedium)}
            item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Row{Text("📊 Today's Progress",fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));Text(done.toString()+" / "+all.size+" completed",fontWeight=FontWeight.Bold)};LinearProgressIndicator({if(all.isEmpty())0f else done.toFloat()/all.size},Modifier.fillMaxWidth().height(8.dp));Text(overdue.toString()+" overdue • "+all.count{!it.done&&it.dueDate==today}+" due today • "+soon+" due soon",style=MaterialTheme.typography.bodySmall)}}}
            item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){StatCard("Pending",all.count{!it.done}.toString(),Modifier.weight(1f));StatCard("Due Soon",soon.toString(),Modifier.weight(1f));StatCard("Overdue",overdue.toString(),Modifier.weight(1f))}}
            item{Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("List","Calendar","Board").forEach{v->FilterChip(view==v,{view=v},label={Text(v)})};Spacer(Modifier.weight(1f));Button({add=true}){Icon(Icons.Default.Add,null);Text(" Add")}}}
            item{Row(Modifier.horizontalScroll(rememberScrollState())){listOf("All","To Do","In progress","Completed").forEach{v->FilterChip(status==v,{status=v},label={Text(v)})};listOf("All","Today","Tomorrow","This Week","Overdue").forEach{v->FilterChip(due==v,{due=v},label={Text(v)})}}}
            item{Row(Modifier.horizontalScroll(rememberScrollState())){listOf("All","High","Medium","Low").forEach{v->FilterChip(priority==v,{priority=v},label={Text(v)})};listOf("All","Assignment","Activity","Project","Quiz","Exam","Report","Presentation","Reading","Requirement","Other").forEach{v->FilterChip(type==v,{type=v},label={Text(v)})}}}
            item{Row(Modifier.horizontalScroll(rememberScrollState())){FilterChip(archived,{archived=!archived},label={Text(if(archived)"Archived" else "Current")});subjects.forEach{s->FilterChip(subject==s.id,{subject=if(subject==s.id)0L else s.id},label={Text(s.title)})}}}
            when(view){"Calendar"->item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp)){TaskCalendar(date){date=it};Text("Tasks on "+date,fontWeight=FontWeight.Bold);list.filter{it.dueDate==date}.forEach{TaskCard(it,store,openSubject,{edit=it},{refresh++})}}}};"Board"->item{Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf("To Do","In Progress","Completed").forEach{c->Column(Modifier.width(280.dp)){Text(c,fontWeight=FontWeight.Bold);list.filter{if(c=="Completed")it.done else if(c=="In Progress")taskInfo(it).status=="In progress"&&!it.done else !it.done&&taskInfo(it).status!="In progress"}.forEach{TaskCard(it,store,openSubject,{edit=it},{refresh++})}}}}};else->items(list,key={it.id}){TaskCard(it,store,openSubject,{edit=it},{refresh++})}}
        }
        Row(Modifier.padding(12.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton({status="All";due="All";priority="All";type="All";subject=0},Modifier.weight(1f)){Text("Clear")};Button({add=true},Modifier.weight(1f)){Text("Add Task")}}
    }
    if(add)TaskEditor(null,store,{add=false;clear();refresh++},{add=false});edit?.let{TaskEditor(it,store,{edit=null;refresh++},{edit=null})}
}

@Composable private fun TaskCard(r:Record,store:LocalStore,openSubject:(Record)->Unit,edit:()->Unit,refresh:()->Unit){
    val m=taskInfo(r);val s=store.get("subjects").firstOrNull{it.id==r.subjectId};val overdue=!r.done&&r.dueDate.isNotBlank()&&r.dueDate<taskDay()
    Card(Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(containerColor=if(overdue)MaterialTheme.colorScheme.errorContainer else MaterialTheme.colorScheme.surface)){Column(Modifier.padding(14.dp)){Row{Column(Modifier.weight(1f)){Text(r.title,fontWeight=FontWeight.Bold);Text(m.type+" • "+m.priority+" • "+m.status,style=MaterialTheme.typography.labelSmall)};IconButton({store.put("tasks",store.get("tasks").map{if(it.id==r.id)it.copy(extra=taskExtra(m.copy(pinned=!m.pinned)))else it});refresh()}){Icon(if(m.pinned)Icons.Default.Star else Icons.Default.StarBorder,null)};Checkbox(r.done,{val n=!r.done;store.put("tasks",store.get("tasks").map{if(it.id==r.id)it.copy(done=n,extra=taskExtra(m.copy(status=if(n)"Completed" else "In progress")))else it});refresh()})};if(s!=null)Text("📚 "+s.title,Modifier.clickable{openSubject(s)},fontWeight=FontWeight.SemiBold);if(r.dueDate.isNotBlank())Text((if(overdue)"⚠ OVERDUE • " else "📅 Due: ")+r.dueDate+" "+r.dueTime);if(m.location.isNotBlank())Text("📍 "+m.location);if(m.link.isNotBlank())Text("🔗 "+m.link);if(m.subtasks.isNotEmpty()){val d=m.subtasks.count{it.second};Text("☑ "+d+" / "+m.subtasks.size+" • "+(d*100/m.subtasks.size)+"%");LinearProgressIndicator({d.toFloat()/m.subtasks.size},Modifier.fillMaxWidth())};if(m.notes.isNotBlank())Text(m.notes,maxLines=2);Row{TextButton({edit()}){Text("Edit")};TextButton({store.put("tasks",store.get("tasks").map{if(it.id==r.id)it.copy(extra=taskExtra(m.copy(archived=!m.archived)))else it})}){Text(if(m.archived)"Unarchive" else "Archive")};TextButton({store.delete("tasks",r.id)}){Text("Delete")}}}}
}

@Composable private fun TaskEditor(record:Record?,store:LocalStore,done:()->Unit,cancel:()->Unit){
    val old=record?.let{taskInfo(it)}?:TaskInfo();var title by remember(record?.id){mutableStateOf(record?.title?:"")};var desc by remember(record?.id){mutableStateOf(record?.subtitle?:"")};var sid by remember(record?.id){mutableLongStateOf(record?.subjectId?:0)};var typ by remember(record?.id){mutableStateOf(old.type)};var pri by remember(record?.id){mutableStateOf(old.priority)};var stat by remember(record?.id){mutableStateOf(old.status)};var dd by remember(record?.id){mutableStateOf(record?.dueDate?:taskDay())};var dt by remember(record?.id){mutableStateOf(record?.dueTime?.ifBlank{"23:59"}?:"23:59")};var rem by remember(record?.id){mutableStateOf(old.reminder)};var loc by remember(record?.id){mutableStateOf(old.location)};var link by remember(record?.id){mutableStateOf(old.link)};var notes by remember(record?.id){mutableStateOf(old.notes)};var sem by remember(record?.id){mutableStateOf(old.semester)};var subs by remember(record?.id){mutableStateOf(old.subtasks)};var ns by remember{mutableStateOf("")};val subjects=store.get("subjects")
    AlertDialog(onDismissRequest=cancel,title={Text(if(record==null)"Add Task" else "Edit Task")},text={Column(Modifier.fillMaxWidth().heightIn(max=680.dp).verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(7.dp)){OutlinedTextField(title,{title=it},Modifier.fillMaxWidth(),label={Text("Task title")});OutlinedTextField(desc,{desc=it},Modifier.fillMaxWidth(),label={Text("Description")});Text("Subject",fontWeight=FontWeight.Bold);Row(Modifier.horizontalScroll(rememberScrollState())){subjects.forEach{s->FilterChip(sid==s.id,{sid=s.id},label={Text(s.title)})}};Text("Task type",fontWeight=FontWeight.Bold);Row(Modifier.horizontalScroll(rememberScrollState())){listOf("Assignment","Activity","Project","Quiz","Exam","Report","Presentation","Reading","Requirement","Other").forEach{v->FilterChip(typ==v,{typ=v},label={Text(v)})}};Text("Priority");Row{listOf("High","Medium","Low").forEach{v->FilterChip(pri==v,{pri=v},label={Text(v)})}};Text("Status");Row{listOf("Not started","In progress","Completed").forEach{v->FilterChip(stat==v,{stat=v},label={Text(v)})}};Row{OutlinedTextField(dd,{dd=it},Modifier.weight(1f),label={Text("Due date")});OutlinedTextField(dt,{dt=it},Modifier.weight(1f),label={Text("Due time")})};Text("Reminder");Row(Modifier.horizontalScroll(rememberScrollState())){listOf("" to "Off","1440" to "1 day","720" to "12 hr","120" to "2 hr","30" to "30 min").forEach{(v,l)->FilterChip(rem==v,{rem=v},label={Text(l)})}};OutlinedTextField(loc,{loc=it},Modifier.fillMaxWidth(),label={Text("Location")});OutlinedTextField(link,{link=it},Modifier.fillMaxWidth(),label={Text("Link")});OutlinedTextField(notes,{notes=it},Modifier.fillMaxWidth(),label={Text("Notes")});Text("Subtasks",fontWeight=FontWeight.Bold);subs.forEachIndexed{i,(t,d)->Row{Checkbox(d,{subs=subs.toMutableList().also{it[i]=t to !d}});Text(t,Modifier.weight(1f));IconButton({subs=subs.toMutableList().also{it.removeAt(i)}}){Icon(Icons.Default.Delete,null)}}};Row{OutlinedTextField(ns,{ns=it},Modifier.weight(1f),label={Text("Checklist item")});IconButton({if(ns.isNotBlank()){subs=subs+(ns.trim() to false);ns=""}}){Icon(Icons.Default.Add,null)}};OutlinedTextField(sem,{sem=it},Modifier.fillMaxWidth(),label={Text("Semester")})}},confirmButton={Button({if(title.isNotBlank()&&sid!=0L){val id=record?.id?:System.currentTimeMillis();val m=old.copy(type=typ,priority=pri,status=stat,reminder=rem,location=loc,link=link,notes=notes,semester=sem,subtasks=subs);val nr=Record(id=id,title=title.trim(),subtitle=desc.trim(),extra=taskExtra(m),done=stat=="Completed",subjectId=sid,dueDate=dd,dueTime=dt);val all=store.get("tasks");store.put("tasks",if(record==null)all+nr else all.map{if(it.id==id)nr else it});done()}}){Text("Save")}},dismissButton={TextButton(cancel){Text("Cancel")}})}
